- name: Preconfigure postfix
  shell: bash -c 'debconf-set-selections <<< "postfix postfix/{{ item.key }} string {{ item.value }}"'
  with_items:
    - {key: 'mailname', value: '{{ mailname }}'}

- name: Install essential packages
  apt: pkg={{ item }} state=installed
  with_items:
    - bcrypt
    - bsd-mailx
    - curl
    - dovecot-core
    - dovecot-imapd
    - dovecot-managesieved
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-mysql
    - git
    - libgpgme11
    - libpth20
    - libpython-stdlib
    - libpython2.7-minimal
    - libpython2.7-stdlib
    - libtokyocabinet9
    - logrotate
    - mysql-client
    - nginx
    - openssh-server
    - php5-cli
    - php5-fpm
    - php5-mysql
    - postfix
    - postfix-mysql
    - postgrey
    - procmail
    - pwgen
    - python
    - python-minimal
    - python2.7
    - python2.7-minimal
    - rsyslog
    - ssl-cert
    - subversion
