- name: Install postfix config files
  copy: src='postfix/{{ item }}' dest=/etc/postfix
  with_items:
    - header_checks

- name: Install postfix config templates
  template: src='postfix/{{ item }}' dest=/etc/postfix
  with_items:
    - main.cf
    - master.cf
    - mysql_sender_login_maps.cf
    - mysql_virtual_alias_maps.cf
    - mysql_virtual_mailbox_limit_maps.cf
    - mysql_virtual_domains_maps.cf
    - mysql_virtual_mailbox_maps.cf

- name: Set mailname
  template: src=mailname dest=/etc/mailname
