- name: Install postfix config files
  copy: src='postfix/{{ item }}' dest=/etc/postfix
  with_items:
    - header_checks

- name: Install postfix config templates
  template: src='postfix/{{ item }}' dest=/etc/postfix
  with_items:
    - main.cf
    - master.cf
    - mysql-sender-login-maps.cf
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-mailbox-limit-maps.cf
    - mysql-virtual-domains-maps.cf
    - mysql-virtual-mailbox-maps.cf
