#!/usr/bin/env sh

if [ "_$RANDOMIZE_PASSWORD" = "_1" ]; then
	ROOT_PASSWORD=`pwgen -c -n -1 12`
	IP_ADDR=`hostname -i`
	echo "IP-Address: $IP_ADDR"
	echo Password: $ROOT_PASSWORD
	echo "root:$ROOT_PASSWORD" | chpasswd
	unset $ROOT_PASSWORD
fi

if [ ! -f /var/lib/clamav/main.cvd ]; then
	chown clamav:clamav /var/lib/clamav
	chmod 770 /var/lib/clamav
fi

if [ ! -d /var/log/clamav ]; then
	mkdir /var/log/clamav
	chown clamav:clamav /var/log/clamav
	chmod 770 /var/log/clamav
fi

if [ -d "$VMAIL_DIR" ]; then
	chown -R $VMAIL_USER:$VMAIL_GROUP $VMAIL_DIR
	chmod 770 $VMAIL_DIR
	find $VMAIL_DIR -type d -exec chmod 770 {} \;
	find $VMAIL_DIR -type f -exec chmod 660 {} \;
fi

# Start system services.
. /etc/default/rsyslog
/usr/sbin/rsyslogd $RSYSLOGD_OPTIONS

# Update ClamAV
/usr/bin/freshclam &

# Start email services.
/usr/sbin/dovecot -c /etc/dovecot/dovecot.conf
service postfix start

# Start email filtering services.
service amavis start
service clamav-daemon start
service postgrey start
service spamassassin start

# Start sshd. The container will stay alive as long as the daemon runs.
# The SSH upstart script that we can't use under docker would have created
# that directory, so we have to do it manually.
test -d /var/run/sshd || mkdir -p -m0755 /var/run/sshd
exec /usr/sbin/sshd -D
